### ISSUE TITLE
Cursor jumps to end

### ISSUE THREAD

**Issue by tomcrabb** [danielyefet/react-input-auto-format#1]
**Describe the bug**
The cursor jumps to the end when adding a character which forces formatting.

**To Reproduce**
1. Using the following code:
```jsx
<Input format="#### ####" />
```
2. Type '123' into the input field
3. Move the cursor left before the '3' and type '4'

**Expected behavior**
The cursor should be between the 4 and the 3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 94

**Comment by danielyefet** [comment]
Cheers @tomcrabb! Fixed in this commit - a1a9fa70523c9a1416636b64b532792da07a5e05
